AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  user-management-system

  Sample SAM Template for user-management-system

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    Runtime: nodejs22.x
    LoggingConfig:
      LogFormat: JSON

Parameters:
  Environment:
    Type: String
    Default: dev
    Description: Environment name

Resources:
  # Cognito User Pool
  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Sub "${Environment}-user-management-pool"
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireUppercase: true
          RequireLowercase: true
          RequireNumbers: true
      AutoVerifiedAttributes:
        - email
      UsernameAttributes:
        - email
      Schema:
        - Name: email
          AttributeDataType: String
          Required: true
        - Name: given_name
          AttributeDataType: String
          Required: true
          Mutable: true
        - Name: family_name
          AttributeDataType: String
          Required: true
          Mutable: true
        - Name: user_role
          AttributeDataType: String
          Required: false
          Mutable: true
          DeveloperOnlyAttribute: false

  # Cognito User Pool Client
  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId: !Ref UserPool
      ClientName: !Sub "${Environment}-user-management-client"
      GenerateSecret: false
      ExplicitAuthFlows:
        - ALLOW_ADMIN_USER_PASSWORD_AUTH
        - ALLOW_USER_PASSWORD_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
      ReadAttributes:
        - email
        - given_name
        - family_name
        - custom:user_role
      WriteAttributes:
        - email
        - given_name
        - family_name
        - custom:user_role

  # API Gateway
  UserManagementApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref Environment
      Cors:
        AllowMethods: "'*'"
        AllowHeaders: "'*'"
        AllowOrigin: "'*'"

  # Login Function
  LoginFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: auth/login.loginHandler
      Runtime: nodejs22.x
      Architectures:
        - x86_64
      Environment:
        Variables:
          USER_POOL_ID: !Ref UserPool
          CLIENT_ID: !Ref UserPoolClient
      Policies:
        - Statement:
          - Effect: Allow
            Action:
              - cognito-idp:AdminInitiateAuth
              - cognito-idp:AdminGetUser
            Resource: !GetAtt UserPool.Arn
      Events:
        LoginApi:
          Type: Api
          Properties:
            RestApiId: !Ref UserManagementApi
            Path: /login
            Method: post

  # Create User Function
  CreateUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: users/createUser.createUserHandler
      Runtime: nodejs22.x
      Architectures:
        - x86_64
      Environment:
        Variables:
          USER_POOL_ID: !Ref UserPool
          CLIENT_ID: !Ref UserPoolClient
      Policies:
        - Statement:
          - Effect: Allow
            Action:
              - cognito-idp:AdminCreateUser
              - cognito-idp:AdminSetUserPassword
              - cognito-idp:AdminGetUser
            Resource: !GetAtt UserPool.Arn
      Events:
        CreateUserApi:
          Type: Api
          Properties:
            RestApiId: !Ref UserManagementApi
            Path: /users
            Method: post

  # List Users Function (SuperAdmin only)
  ListUsersFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: users/listUsers.listUsersHandler
      Runtime: nodejs22.x
      Architectures:
        - x86_64
      Environment:
        Variables:
          USER_POOL_ID: !Ref UserPool
          CLIENT_ID: !Ref UserPoolClient
      Policies:
        - Statement:
          - Effect: Allow
            Action:
              - cognito-idp:ListUsers
              - cognito-idp:AdminGetUser
            Resource: !GetAtt UserPool.Arn
      Events:
        ListUsersApi:
          Type: Api
          Properties:
            RestApiId: !Ref UserManagementApi
            Path: /users
            Method: get

  # Get User Info Function (Admin only)
  GetUserInfoFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: users/getUserInfo.getUserInfoHandler
      Runtime: nodejs22.x
      Architectures:
        - x86_64
      Environment:
        Variables:
          USER_POOL_ID: !Ref UserPool
          CLIENT_ID: !Ref UserPoolClient
      Events:
        GetUserInfoApi:
          Type: Api
          Properties:
            RestApiId: !Ref UserManagementApi
            Path: /me
            Method: get

Outputs:
  UserManagementApi:
    Description: API Gateway endpoint URL for user management
    Value: !Sub "https://${UserManagementApi}.execute-api.${AWS::Region}.amazonaws.com/${Environment}/"

  UserPoolId:
    Description: Cognito User Pool ID
    Value: !Ref UserPool

  UserPoolClientId:
    Description: Cognito User Pool Client ID
    Value: !Ref UserPoolClient

  LoginApi:
    Description: API Gateway endpoint URL for Login
    Value: !Sub "https://${UserManagementApi}.execute-api.${AWS::Region}.amazonaws.com/${Environment}/login"

  LoginFunction:
    Description: Login Lambda Function ARN
    Value: !GetAtt LoginFunction.Arn

  CreateUserApi:
    Description: API Gateway endpoint URL for Create User
    Value: !Sub "https://${UserManagementApi}.execute-api.${AWS::Region}.amazonaws.com/${Environment}/users"

  CreateUserFunction:
    Description: Create User Lambda Function ARN
    Value: !GetAtt CreateUserFunction.Arn

  ListUsersApi:
    Description: API Gateway endpoint URL for List Users
    Value: !Sub "https://${UserManagementApi}.execute-api.${AWS::Region}.amazonaws.com/${Environment}/users"

  ListUsersFunction:
    Description: List Users Lambda Function ARN
    Value: !GetAtt ListUsersFunction.Arn

  GetUserInfoApi:
    Description: API Gateway endpoint URL for Get User Info
    Value: !Sub "https://${UserManagementApi}.execute-api.${AWS::Region}.amazonaws.com/${Environment}/me"

  GetUserInfoFunction:
    Description: Get User Info Lambda Function ARN
    Value: !GetAtt GetUserInfoFunction.Arn
